name: Main Branch 

on:
  push: 
    branches: [main]

jobs:
  build:
    uses: ./.github/workflows/install-dependencies.yml
    with:
      command: yarn build
        
  eslint:
    uses: ./.github/workflows/install-dependencies.yml
    with:
      command: yarn lint

  unit-test:
    uses: ./.github/workflows/install-dependencies.yml
    with:
      command: yarn test
